djflow/apps/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<str:room_name>/', views.room, name='room'),
]

djflow/apps/flow/urls.py
from django.conf.urls import url
from .views import Dashboard, AccountList, AccountNew, AccountDelete, AccountEdit
from .views import TransactionList, TransactionNew, TransactionEdit, TransactionDelete
from .views import CategoryList, CategoryNew, CategoryEdit, CategoryDelete
from .views import TransactionCommentList, TransactionCommentNew

app_name = 'flow'

urlpatterns = [
    url(r'dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'flow/account/list/$', AccountList.as_view(), name="account-list"),
    url(r'flow/account/new/$', AccountNew.as_view(), name="account-new"),
    url(r'flow/account/delete/(?P<pk>.*)/$', AccountDelete.as_view(), name="account-delete"),
    url(r'flow/account/edit/(?P<pk>.*)/$', AccountEdit.as_view(), name="account-edit"),
    url(r'flow/transaction/list/$', TransactionList.as_view(), name="transaction-list"),
    url(r'flow/transaction/new/$', TransactionNew.as_view(), name="transaction-new"),
    url(r'flow/transaction/edit/(?P<pk>.*)/$', TransactionEdit.as_view(), name="transaction-edit"),
    url(r'flow/transaction/delete/(?P<pk>.*)/$', TransactionDelete.as_view(), name="transaction-delete"),
    url(r'flow/category/list/$', CategoryList.as_view(), name="category-list"),
    url(r'flow/category/new/$', CategoryNew.as_view(), name="category-new"),
    url(r'flow/category/edit/(?P<pk>.*)/$', CategoryEdit.as_view(), name="category-edit"),
    url(r'flow/category/delete/(?P<pk>.*)/$', CategoryDelete.as_view(), name="category-delete"),
    url(r'flow/transaction/comment/list/$', TransactionCommentList.as_view(), name="transaction-comment-list"),
    url(r'flow/transaction/(?P<trans_id>.*)/comment/new/$', TransactionCommentNew.as_view(), name="transaction-comment-new"),
]

djflow/apps/security/urls.py
from django.conf.urls import url
from .views import Login, Logout
from .views import UserProfileData, UserList, UserNew, UserDelete
from .views import ActiveInactiveUser, ChangePassword
from .views import TenantRegisterView, PreLoginView

app_name = 'security'

urlpatterns = [
    url(r'^login/$', Login.as_view(), name="login"),
    url(r'^logout/$', Logout.as_view(), name="logout"),
    url(r'^userprofile/$', UserProfileData.as_view(), name="userprofile"),
    url(r'^userprofilechange-password/$', ChangePassword.as_view(), name="userprofile-change-password"),
    url(r'^user/list/$', UserList.as_view(), name="user-list"),
    url(r'^user/new/$', UserNew.as_view(), name="user-new"),
    url(r'^user/delete/(?P<pk>.*)/$', UserDelete.as_view(), name="user-delete"),
    url(r'^user/active-inactive/(?P<user_id>.*)/$', ActiveInactiveUser.as_view(), name="user-active-inactive"),
    url(r'^tenant/register/$', TenantRegisterView.as_view(), name="tenant-register"),
    url(r'^pre-login/$', PreLoginView.as_view(), name="pre-login"),
]

djflow/apps/website/urls.py
from django.conf.urls import url
from .views import Index

app_name = 'website'

urlpatterns = [
    url(r'^$', Index.as_view(), name="index"),
]

djflow/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from djflow.apps.chat import views
from djflow.core.json_settings import get_settings
from django.views.static import serve

settings_json = get_settings()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djflow.apps.website.urls')),
    url(r'^chat/', include('djflow.apps.chat.urls'), name='room'),
    url(r'^flow/', include('djflow.apps.flow.urls')),
    url(r'^security/', include('djflow.apps.security.urls')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings_json["DEBUG"]:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djflow/apps/chat/models.py
from django.db import models

# Create your models here.

djflow/apps/flow/models.py
from django.db.models import Sum
from django.db import models
from django.utils.translation import ugettext as _

from django.contrib.auth.models import User


class Account(models.Model):
    """
    Cuentas del usuario
    """
    created_by = models.ForeignKey(User, help_text=_("Usuario que ha creado la cuenta"), on_delete=models.PROTECT)
    name = models.CharField(max_length=1000, verbose_name=_("Nombre"))
    description = models.TextField(max_length=1000, verbose_name=_("Descripción"), null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, help_text=_("Fecha de creación"))
    is_active = models.BooleanField(default=True, help_text=_("¿Se puede utilizar esta cuenta o está inactiva?"))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )
        verbose_name = _("Cuenta")
        verbose_name_plural = _("Cuentas")


class Category(models.Model):
    TYPE_OPTIONS = (
        (0, _("Egreso")),
        (1, _("Ingreso"))
    )

    name = models.CharField(max_length=500)
    type = models.IntegerField(choices=TYPE_OPTIONS, default=1)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.type == 0:
            return "[Egreso] {0}".format(self.name)
        else:
            return "[Ingreso] {0}".format(self.name)

    class Meta:
        ordering = ('name', )
        verbose_name = _("Categoría")
        verbose_name_plural = _("Categorías")


class Transaction(models.Model):
    """
    Registra los ingresos / egresos
    """

    created_by = models.ForeignKey(User, help_text=_("Usuario que ha creado la cuenta"), on_delete=models.PROTECT)
    account = models.ForeignKey(Account, help_text=_("Cuenta a afectar"), verbose_name=_("Cuenta"), on_delete=models.PROTECT)
    name = models.CharField(max_length=500, verbose_name=_("Descripción"))
    category = models.ForeignKey(Category, verbose_name=_("Categoría"), on_delete=models.PROTECT)
    amount = models.DecimalField(decimal_places=2, max_digits=12, verbose_name=_("Monto"))
    date = models.DateField(help_text=_("Fecha del movimiento"), verbose_name=_("Fecha"))
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-date",)
        verbose_name = _("Transacción")
        verbose_name_plural = _("Transacciones")


class TransactionComment(models.Model):
    transaction = models.ForeignKey(Transaction, verbose_name=_("Transacción"), on_delete=models.PROTECT)
    created_by = models.ForeignKey(User, verbose_name=_("Usuario"), on_delete=models.PROTECT)
    comment = models.TextField(max_length=1200, verbose_name=_("Comentario"))
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

    class Meta:
        ordering = ('-timestamp', )
        verbose_name = _("Comentario de la transacción")
        verbose_name_plural = _("Comentarios de transacciones")

djflow/apps/security/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone
from tenant_schemas.utils import connection


class UserProfile(models.Model):

    def image_path(self, filename):
        extension = os.path.splitext(filename)[1][1:]
        file_name = os.path.splitext(filename)[0]
        url = "%s/Users/%s/profile/%s.%s" % (connection.tenant.domain_url, self.user.id, slugify(str(file_name)), extension)
        return url

    user = models.OneToOneField(User, on_delete=models.PROTECT)
    image_profile = models.ImageField(upload_to=image_path, null=True, blank=True)

    def __str__(self):
        return self.user.get_full_name()


# ============================================================
# Conectamos signals.
# ============================================================

from .signals import *

djflow/apps/flow/forms.py
from django import forms
from django.utils import timezone
from .models import Transaction
from django.utils.translation import ugettext as _
from djflow.core.internationalization import DATE_INPUT_FORMATS


class TransactionForm(forms.ModelForm):
    date = forms.DateField(input_formats=DATE_INPUT_FORMATS)

    class Meta:
        model = Transaction
        fields = ['account', 'name', 'category', 'amount', 'date']

djflow/apps/chat/views.py
# chat/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html', {})

def room(request, room_name):
    return render(request, 'chat.html', {
        'room_name': room_name
    })

djflow/apps/flow/views.py
from django.db.models import Sum
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import View, ListView, CreateView, DeleteView, UpdateView
from django.contrib import messages

from djflow.apps import response_messages
from .models import Account, Transaction, Category, TransactionComment
from .forms import TransactionForm
import logging

logger = logging.getLogger(__name__)
# =================================================================
# Cuentas
# =================================================================


class Dashboard(LoginRequiredMixin, View):
    template_name = "dashboard.html"

    @staticmethod
    def expenses_by_category():
        """
        Obtenemos gastos por categoría
        :return: queryset
        """
        categories = Category.objects.filter(type=0)
        categories = categories.annotate(total_amount=Sum('transaction__amount')).order_by('total_amount')
        categories = categories[:5]
        return categories

    @staticmethod
    def incomes_by_category():
        """
        Obtenemos ingresos por categoría
        :return: queryset
        """
        categories = Category.objects.filter(type=1)
        categories = categories.annotate(total_amount=Sum('transaction__amount')).order_by('total_amount')
        categories = categories[:5]
        return categories

    def get(self, request):
        logger.info('info from view')
        logger.debug("debug from view")
        logger.error("error from view")
        number_of_registers = 5
        accounts_qs = Account.objects.filter(is_active=True).order_by('timestamp')[:number_of_registers]
        accounts_qs = accounts_qs.annotate(total_amount=Sum('transaction__amount'))
        transactions_accounts = Transaction.objects.filter(account__in=accounts_qs).order_by('-timestamp')[:number_of_registers]
        expense_categories = self.expenses_by_category()
        income_categories = self.incomes_by_category()
        ctx = {
            'accounts': accounts_qs,
            'expense_categories': expense_categories,
            'income_categories': income_categories,
            'transactions': transactions_accounts,
        }
        return render(request, self.template_name, ctx)


class AccountList(LoginRequiredMixin, ListView):
    template_name = "account_list.html"
    model = Account
    paginate_by = 10


class AccountNew(LoginRequiredMixin, CreateView):
    template_name = "account_new.html"
    model = Account
    fields = ['name', 'description']
    success_url = reverse_lazy('flow:account-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.SAVE_SUCCESSFULL)
        form.instance.created_by = self.request.user
        return super(AccountNew, self).form_valid(form)


class AccountEdit(LoginRequiredMixin, UpdateView):
    template_name = "account_edit.html"
    model = Account
    fields = ['name', 'description']
    success_url = reverse_lazy('flow:account-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.UPDATE_SUCCESSFULL)
        return super(AccountEdit, self).form_valid(form)


class AccountDelete(LoginRequiredMixin, DeleteView):
    template_name = "account_delete.html"
    model = Account
    success_url = reverse_lazy('flow:account-list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, response_messages.DELETE_SUCCESSFULL)
        return super(AccountDelete, self).delete(request, *args, **kwargs)


# =================================================================
# Transacciones
# =================================================================


class TransactionList(LoginRequiredMixin, ListView):
    template_name = "transaction_list.html"
    model = Transaction
    paginate_by = 10


class TransactionNew(LoginRequiredMixin, CreateView):
    template_name = "transaction_new.html"
    model = Transaction
    success_url = reverse_lazy('flow:transaction-list')
    form_class = TransactionForm

    def form_valid(self, form):
        messages.success(self.request, response_messages.SAVE_SUCCESSFULL)
        form.instance.created_by = self.request.user
        if form.instance.category.type == 0:
            form.instance.amount = -form.instance.amount
        return super(TransactionNew, self).form_valid(form)


class TransactionEdit(LoginRequiredMixin, UpdateView):
    template_name = "transaction_edit.html"
    model = Transaction
    form_class = TransactionForm
    success_url = reverse_lazy('flow:transaction-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.UPDATE_SUCCESSFULL)
        if form.instance.category.type == 0:
            if form.instance.amount > 0:
                form.instance.amount = -form.instance.amount
        else:
            if form.instance.amount < 0:
                form.instance.amount = abs(form.instance.amount)
        return super(TransactionEdit, self).form_valid(form)


class TransactionDelete(LoginRequiredMixin, DeleteView):
    template_name = "transaction_delete.html"
    model = Transaction
    success_url = reverse_lazy('flow:transaction-list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, response_messages.DELETE_SUCCESSFULL)
        return super(TransactionDelete, self).delete(request, *args, **kwargs)


# =================================================================
# Categorías
# =================================================================

class CategoryList(LoginRequiredMixin, ListView):
    template_name = "category_list.html"
    model = Category
    paginate_by = 10


class CategoryNew(LoginRequiredMixin, CreateView):
    template_name = "category_new.html"
    model = Category
    fields = ['name', 'type']
    success_url = reverse_lazy('flow:category-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.SAVE_SUCCESSFULL)
        form.instance.created_by = self.request.user
        return super(CategoryNew, self).form_valid(form)


class CategoryEdit(LoginRequiredMixin, UpdateView):
    template_name = "category_new.html"
    model = Category
    fields = ['name', 'type']
    success_url = reverse_lazy('flow:category-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.UPDATE_SUCCESSFULL)
        return super(CategoryEdit, self).form_valid(form)


class CategoryDelete(LoginRequiredMixin, DeleteView):
    template_name = "category_delete.html"
    model = Category
    success_url = reverse_lazy('flow:category-list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, response_messages.DELETE_SUCCESSFULL)
        return super(CategoryDelete, self).delete(request, *args, **kwargs)


# =================================================================
# Comentarios
# =================================================================


class TransactionCommentList(ListView):
    template_name = "comment_list.html"
    model = TransactionComment
    paginate_by = 100

    def get_queryset(self):
        if self.request.GET.get("transaction"):
            queryset = TransactionComment.objects.filter(transaction__id=self.request.GET.get("transaction"))
        else:
            queryset = TransactionComment.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(TransactionCommentList, self).get_context_data(**kwargs)
        try:
            context['transaction'] = Transaction.objects.get(id=self.request.GET.get("transaction"))
        except:
            context['transaction'] = None
        return context


class TransactionCommentNew(View):

    def get(self, request, trans_id):
        url = reverse_lazy('flow:transaction-comment-list')
        url += "?transaction={0}".format(trans_id)
        return HttpResponseRedirect(url)

    def post(self, request, trans_id):
        try:
            transaction = Transaction.objects.get(id=trans_id)
        except:
            transaction = None
        if transaction:
            new_comment = TransactionComment()
            new_comment.transaction = transaction
            new_comment.comment = request.POST['comment']
            new_comment.created_by = request.user
            new_comment.save()
            messages.success(request, response_messages.SAVE_SUCCESSFULL)
        else:
            messages.error(request, response_messages.SAVE_ERROR)
        url = reverse_lazy('flow:transaction-comment-list')
        url += "?transaction={0}".format(trans_id)
        return HttpResponseRedirect(url)

djflow/apps/tenant/views.py
from django.shortcuts import render

# Create your views here.

djflow/apps/website/views.py
from django.views.generic import TemplateView


class Index(TemplateView):
    template_name = "index.html"

djflow/templates/base.html
{% load i18n static solo_tags %}
{% get_solo 'website.SiteConfiguration' as site_config %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}{{ site_config.site_name }}{% endblock title %}</title>
    <link href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'libs/jquery-ui/jquery-ui.css' %}">
{#    <link rel="stylesheet" href="{% static 'libs/jquery-ui/themes/jquery-ui.min.css' %}">#}
    <link href="{% static 'libs/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock extra_css %}
</head>
<body>
 <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'flow:dashboard' %}">{{ site_config.site_name }}</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
        </ul>
        <form class="form-inline mt-3 mt-md-0">
            <a href="{% url 'security:userprofile' %}">
                {% if not user.userprofile.image_profile %}
                <i style="color:white;" class="fa fa-user pull-right fa-2x"></i>
                {% else %}
                    <img class="rounded mx-auto" src="{{ user.userprofile.image_profile.url }}" alt="" width="32px" height="32px">
                {% endif %}
            </a>
            <a href="{% url 'security:logout' %}"> <i style="color:white;" class="fa fa-power-off pull-right fa-2x"></i></a>
        </form>
      </div>
    </nav>
<div class="container-fluid">
    <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                    <a class="nav-link  {% block nav_dashboard %}{% endblock %}" href="{% url 'flow:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block nav_transac %}{% endblock %}" href="{% url 'flow:transaction-list' %}">{% trans 'Transacciones' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block nav_category %}{% endblock %}" href="{% url 'flow:category-list' %}">{% trans 'Categorías' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block nav_cuentas %}{% endblock %}" href="{% url 'flow:account-list' %}">{% trans 'Cuentas' %}</a>
                </li>
            {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link {% block nav_users %}{% endblock %}" href="{% url 'security:user-list' %}">{% trans 'Usuarios' %}</a>
                </li>
            {% endif %}
            </ul>
        </nav>
        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags == 'success' %}alert-success{% else %}alert-danger{% endif %} alert-dismissible fade show" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
            <h1>
                {% block page-title %} {% endblock page-title %}
                <div class="float-right">
                    {% block add-button %}
                        {#                        <a href="#" class="btn btn-primary"><i class="fa fa-plus"></i> {% trans 'Nuevo' %}</a>#}
                    {% endblock add-button %}
                </div>
            </h1>
            {% block content %}
            {% endblock content %}
        </main>
    </div>
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'libs/jquery/jquery-1.12.4.js' %}"></script>
<script src="{% static 'libs/jquery-ui/jquery-ui.js' %}"></script>
<script src="{% static 'libs/popper/popper.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'libs/ie10/ie10-viewport-bug-workaround.js' %}"></script>
 <script>
  $( function() {
    $( ".datepicker" ).datepicker({
        dateFormat: "dd-mm-yy"
    });
  } );
  </script>
{% block extra_js %} {% endblock extra_js %}
</body>
</html>

djflow/templates/base_website.html
{% load i18n static solo_tags %}
{% get_solo 'website.SiteConfiguration' as site_config %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <title>{{ site_config.site_name }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>

<body>

<div class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="cover-container">

            <div class="masthead clearfix">
                <div class="inner">
                    <h3 class="masthead-brand"><a href="/">{{ site_config.site_name }}</a></h3>
                    <nav class="nav nav-masthead">
                        <a class="nav-link {% if active_menu != "register" %}active{% endif %}" href="{% url 'security:login' %}">{% trans 'Ingresar' %}</a>
                        <a class="nav-link {% if active_menu == "register" %}active{% endif %}" href="{% url 'security:tenant-register' %}">{% trans 'Registrarse' %}</a>
{#                        <a class="nav-link" href="#">Contact</a>#}
                    </nav>
                </div>
            </div>
{% block content %}


                    <!-- content here -->

            </div>
            {% endblock content %}
            <div class="mastfoot">
                <div class="inner">
                    <p>Powered by <a href="https://github.com/kiubtech/djflow"> Open Source Software</a>, written by <a
                            href="https://twitter.com/kiubtech/">@kiubtech</a>.</p>
                </div>
            </div>

        </div>

    </div>

</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'libs/jquery/jquery-1.12.4.js' %}"></script>
<script src="{% static 'libs/popper/popper.min.js' %}"></script>
<script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'libs/ie10/ie10-viewport-bug-workaround.js' %}"></script>
</body>
</html>

djflow/templates/chat.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
<input id="chat-message-input" type="text" size="100"><br>
<input id="chat-message-submit" type="button" value="Send">
{{ room_name|json_script:"room-name" }}
<script>
    window.addEventListener('DOMContentLoaded', () => {
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        const protocol = window.location.protocol.indexOf("https") > -1? "wss":"ws";

        const chatSocket = new WebSocket(`${protocol}://${window.location.host}/chatear/usuario/${roomName}/`);

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onopen = function (e) {
            console.log('Chat socket is open');
        };

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    });
</script>
</body>
</html>

djflow/templates/index.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
<input id="chat-message-input" type="text" size="100"><br>
<input id="chat-message-submit" type="button" value="Send">
{{ room_name|json_script:"room-name" }}
<script>
    window.addEventListener('DOMContentLoaded', () => {
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(`ws://${window.location.host}/chatear/usuario/${roomName}/`);

        chatSocket.onmessage = function (e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onopen = function (e) {
            console.log('Chat socket is open');
        };

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function (e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    });
</script>
</body>
</html>