djflow/apps/flow/urls.py
from django.conf.urls import url
from .views import Dashboard, AccountList, AccountNew, AccountDelete, AccountEdit
from .views import TransactionList, TransactionNew, TransactionEdit, TransactionDelete
from .views import CategoryList, CategoryNew, CategoryEdit, CategoryDelete
from .views import TransactionCommentList, TransactionCommentNew

app_name = 'flow'

urlpatterns = [
    url(r'dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'flow/account/list/$', AccountList.as_view(), name="account-list"),
    url(r'flow/account/new/$', AccountNew.as_view(), name="account-new"),
    url(r'flow/account/delete/(?P<pk>.*)/$', AccountDelete.as_view(), name="account-delete"),
    url(r'flow/account/edit/(?P<pk>.*)/$', AccountEdit.as_view(), name="account-edit"),
    url(r'flow/transaction/list/$', TransactionList.as_view(), name="transaction-list"),
    url(r'flow/transaction/new/$', TransactionNew.as_view(), name="transaction-new"),
    url(r'flow/transaction/edit/(?P<pk>.*)/$', TransactionEdit.as_view(), name="transaction-edit"),
    url(r'flow/transaction/delete/(?P<pk>.*)/$', TransactionDelete.as_view(), name="transaction-delete"),
    url(r'flow/category/list/$', CategoryList.as_view(), name="category-list"),
    url(r'flow/category/new/$', CategoryNew.as_view(), name="category-new"),
    url(r'flow/category/edit/(?P<pk>.*)/$', CategoryEdit.as_view(), name="category-edit"),
    url(r'flow/category/delete/(?P<pk>.*)/$', CategoryDelete.as_view(), name="category-delete"),
    url(r'flow/transaction/comment/list/$', TransactionCommentList.as_view(), name="transaction-comment-list"),
    url(r'flow/transaction/(?P<trans_id>.*)/comment/new/$', TransactionCommentNew.as_view(), name="transaction-comment-new"),
]

djflow/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path
from djflow.apps.chat import views
from djflow.core.json_settings import get_settings
from django.views.static import serve

settings_json = get_settings()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('djflow.apps.website.urls')),
    url(r'^chat/', include('djflow.apps.chat.urls'), name='room'),
    url(r'^flow/', include('djflow.apps.flow.urls')),
    url(r'^security/', include('djflow.apps.security.urls')),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

if settings_json["DEBUG"]:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djflow/apps/flow/models.py
from django.db.models import Sum
from django.db import models
from django.utils.translation import ugettext as _

from django.contrib.auth.models import User


class Account(models.Model):
    """
    Cuentas del usuario
    """
    created_by = models.ForeignKey(User, help_text=_("Usuario que ha creado la cuenta"), on_delete=models.PROTECT)
    name = models.CharField(max_length=1000, verbose_name=_("Nombre"))
    description = models.TextField(max_length=1000, verbose_name=_("Descripción"), null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True, help_text=_("Fecha de creación"))
    is_active = models.BooleanField(default=True, help_text=_("¿Se puede utilizar esta cuenta o está inactiva?"))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name', )
        verbose_name = _("Cuenta")
        verbose_name_plural = _("Cuentas")


class Category(models.Model):
    TYPE_OPTIONS = (
        (0, _("Egreso")),
        (1, _("Ingreso"))
    )

    name = models.CharField(max_length=500)
    type = models.IntegerField(choices=TYPE_OPTIONS, default=1)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.type == 0:
            return "[Egreso] {0}".format(self.name)
        else:
            return "[Ingreso] {0}".format(self.name)

    class Meta:
        ordering = ('name', )
        verbose_name = _("Categoría")
        verbose_name_plural = _("Categorías")


class Transaction(models.Model):
    """
    Registra los ingresos / egresos
    """

    created_by = models.ForeignKey(User, help_text=_("Usuario que ha creado la cuenta"), on_delete=models.PROTECT)
    account = models.ForeignKey(Account, help_text=_("Cuenta a afectar"), verbose_name=_("Cuenta"), on_delete=models.PROTECT)
    name = models.CharField(max_length=500, verbose_name=_("Descripción"))
    category = models.ForeignKey(Category, verbose_name=_("Categoría"), on_delete=models.PROTECT)
    amount = models.DecimalField(decimal_places=2, max_digits=12, verbose_name=_("Monto"))
    date = models.DateField(help_text=_("Fecha del movimiento"), verbose_name=_("Fecha"))
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-date",)
        verbose_name = _("Transacción")
        verbose_name_plural = _("Transacciones")


class TransactionComment(models.Model):
    transaction = models.ForeignKey(Transaction, verbose_name=_("Transacción"), on_delete=models.PROTECT)
    created_by = models.ForeignKey(User, verbose_name=_("Usuario"), on_delete=models.PROTECT)
    comment = models.TextField(max_length=1200, verbose_name=_("Comentario"))
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment

    class Meta:
        ordering = ('-timestamp', )
        verbose_name = _("Comentario de la transacción")
        verbose_name_plural = _("Comentarios de transacciones")

djflow/apps/flow/forms.py
from django import forms
from django.utils import timezone
from .models import Transaction
from django.utils.translation import ugettext as _
from djflow.core.internationalization import DATE_INPUT_FORMATS


class TransactionForm(forms.ModelForm):
    date = forms.DateField(input_formats=DATE_INPUT_FORMATS)

    class Meta:
        model = Transaction
        fields = ['account', 'name', 'category', 'amount', 'date']

djflow/apps/flow/views.py
from django.db.models import Sum
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import View, ListView, CreateView, DeleteView, UpdateView
from django.contrib import messages

from djflow.apps import response_messages
from .models import Account, Transaction, Category, TransactionComment
from .forms import TransactionForm
import logging

logger = logging.getLogger(__name__)
# =================================================================
# Cuentas
# =================================================================


class Dashboard(LoginRequiredMixin, View):
    template_name = "dashboard.html"

    @staticmethod
    def expenses_by_category():
        """
        Obtenemos gastos por categoría
        :return: queryset
        """
        categories = Category.objects.filter(type=0)
        categories = categories.annotate(total_amount=Sum('transaction__amount')).order_by('total_amount')
        categories = categories[:5]
        return categories

    @staticmethod
    def incomes_by_category():
        """
        Obtenemos ingresos por categoría
        :return: queryset
        """
        categories = Category.objects.filter(type=1)
        categories = categories.annotate(total_amount=Sum('transaction__amount')).order_by('total_amount')
        categories = categories[:5]
        return categories

    def get(self, request):
        logger.info('info from view')
        logger.debug("debug from view")
        logger.error("error from view")
        number_of_registers = 5
        accounts_qs = Account.objects.filter(is_active=True).order_by('timestamp')[:number_of_registers]
        accounts_qs = accounts_qs.annotate(total_amount=Sum('transaction__amount'))
        transactions_accounts = Transaction.objects.filter(account__in=accounts_qs).order_by('-timestamp')[:number_of_registers]
        expense_categories = self.expenses_by_category()
        income_categories = self.incomes_by_category()
        ctx = {
            'accounts': accounts_qs,
            'expense_categories': expense_categories,
            'income_categories': income_categories,
            'transactions': transactions_accounts,
        }
        return render(request, self.template_name, ctx)


class AccountList(LoginRequiredMixin, ListView):
    template_name = "account_list.html"
    model = Account
    paginate_by = 10


class AccountNew(LoginRequiredMixin, CreateView):
    template_name = "account_new.html"
    model = Account
    fields = ['name', 'description']
    success_url = reverse_lazy('flow:account-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.SAVE_SUCCESSFULL)
        form.instance.created_by = self.request.user
        return super(AccountNew, self).form_valid(form)


class AccountEdit(LoginRequiredMixin, UpdateView):
    template_name = "account_edit.html"
    model = Account
    fields = ['name', 'description']
    success_url = reverse_lazy('flow:account-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.UPDATE_SUCCESSFULL)
        return super(AccountEdit, self).form_valid(form)


class AccountDelete(LoginRequiredMixin, DeleteView):
    template_name = "account_delete.html"
    model = Account
    success_url = reverse_lazy('flow:account-list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, response_messages.DELETE_SUCCESSFULL)
        return super(AccountDelete, self).delete(request, *args, **kwargs)


# =================================================================
# Transacciones
# =================================================================


class TransactionList(LoginRequiredMixin, ListView):
    template_name = "transaction_list.html"
    model = Transaction
    paginate_by = 10


class TransactionNew(LoginRequiredMixin, CreateView):
    template_name = "transaction_new.html"
    model = Transaction
    success_url = reverse_lazy('flow:transaction-list')
    form_class = TransactionForm

    def form_valid(self, form):
        messages.success(self.request, response_messages.SAVE_SUCCESSFULL)
        form.instance.created_by = self.request.user
        if form.instance.category.type == 0:
            form.instance.amount = -form.instance.amount
        return super(TransactionNew, self).form_valid(form)


class TransactionEdit(LoginRequiredMixin, UpdateView):
    template_name = "transaction_edit.html"
    model = Transaction
    form_class = TransactionForm
    success_url = reverse_lazy('flow:transaction-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.UPDATE_SUCCESSFULL)
        if form.instance.category.type == 0:
            if form.instance.amount > 0:
                form.instance.amount = -form.instance.amount
        else:
            if form.instance.amount < 0:
                form.instance.amount = abs(form.instance.amount)
        return super(TransactionEdit, self).form_valid(form)


class TransactionDelete(LoginRequiredMixin, DeleteView):
    template_name = "transaction_delete.html"
    model = Transaction
    success_url = reverse_lazy('flow:transaction-list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, response_messages.DELETE_SUCCESSFULL)
        return super(TransactionDelete, self).delete(request, *args, **kwargs)


# =================================================================
# Categorías
# =================================================================

class CategoryList(LoginRequiredMixin, ListView):
    template_name = "category_list.html"
    model = Category
    paginate_by = 10


class CategoryNew(LoginRequiredMixin, CreateView):
    template_name = "category_new.html"
    model = Category
    fields = ['name', 'type']
    success_url = reverse_lazy('flow:category-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.SAVE_SUCCESSFULL)
        form.instance.created_by = self.request.user
        return super(CategoryNew, self).form_valid(form)


class CategoryEdit(LoginRequiredMixin, UpdateView):
    template_name = "category_new.html"
    model = Category
    fields = ['name', 'type']
    success_url = reverse_lazy('flow:category-list')

    def form_valid(self, form):
        messages.success(self.request, response_messages.UPDATE_SUCCESSFULL)
        return super(CategoryEdit, self).form_valid(form)


class CategoryDelete(LoginRequiredMixin, DeleteView):
    template_name = "category_delete.html"
    model = Category
    success_url = reverse_lazy('flow:category-list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, response_messages.DELETE_SUCCESSFULL)
        return super(CategoryDelete, self).delete(request, *args, **kwargs)


# =================================================================
# Comentarios
# =================================================================


class TransactionCommentList(ListView):
    template_name = "comment_list.html"
    model = TransactionComment
    paginate_by = 100

    def get_queryset(self):
        if self.request.GET.get("transaction"):
            queryset = TransactionComment.objects.filter(transaction__id=self.request.GET.get("transaction"))
        else:
            queryset = TransactionComment.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(TransactionCommentList, self).get_context_data(**kwargs)
        try:
            context['transaction'] = Transaction.objects.get(id=self.request.GET.get("transaction"))
        except:
            context['transaction'] = None
        return context


class TransactionCommentNew(View):

    def get(self, request, trans_id):
        url = reverse_lazy('flow:transaction-comment-list')
        url += "?transaction={0}".format(trans_id)
        return HttpResponseRedirect(url)

    def post(self, request, trans_id):
        try:
            transaction = Transaction.objects.get(id=trans_id)
        except:
            transaction = None
        if transaction:
            new_comment = TransactionComment()
            new_comment.transaction = transaction
            new_comment.comment = request.POST['comment']
            new_comment.created_by = request.user
            new_comment.save()
            messages.success(request, response_messages.SAVE_SUCCESSFULL)
        else:
            messages.error(request, response_messages.SAVE_ERROR)
        url = reverse_lazy('flow:transaction-comment-list')
        url += "?transaction={0}".format(trans_id)
        return HttpResponseRedirect(url)

djflow/apps/flow/templates/account_delete.html
{% extends 'base.html' %}
{% load i18n static add_class %}
{% block title %}{% trans 'Eliminar cuenta' %}{% endblock %}
{% block page-title %}{% trans 'Eliminar cuenta' %}{% endblock %}
{% block nav_cuentas %}active{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h3 class="text-center">{% trans '¿Seguro que deseas eliminar este elemento?' %}</h3>
        <form action="." method="post">
            {% csrf_token %}

            <p class="text-center">
                <a href="{% url 'flow:account-list' %}" class="btn btn-secondary">{% trans 'Regresar' %}</a>
                <input class="btn btn-danger" type="submit" value="{% trans 'Eliminar' %}">
            </p>

        </form>
    </div>

{% endblock content %}

djflow/apps/flow/templates/account_list.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{% trans 'Cuentas' %}{% endblock %}
{% block page-title %}{% trans 'Cuentas' %}{% endblock %}
{% block nav_cuentas %}active{% endblock %}
{% block add-button %}
     <a href="{% url 'flow:account-new' %}" class="btn btn-outline-primary"><i class="fa fa-plus"></i> {% trans 'Nuevo' %}</a>
{% endblock %}
{% block content %}
    {% if object_list %}
        <table class="table table-sm">
            <thead class="thead-inverse">
            <tr>
                <th>{% trans 'Nombre' %}</th>
                <th>{% trans 'Descripción' %}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for element in object_list %}
                <tr>
                    <td><a href="{% url 'flow:account-edit' element.pk %}">{{ element.name }}</a></td>
                    <td>{{ element.description }}</td>
                    <td><a href="{% url 'flow:account-delete' element.pk %}" class="btn btn-danger btn-sm btn-flat"><i class="fa fa-trash"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'includes/paginator.html' with url_list='/flow/account/list/' %}
    {% else %}
        <div class="alert alert-info" role="alert">
            <span>{% trans 'Parece que aún no hay cuentas registradas' %}</span>
        </div>
    {% endif %}
{% endblock content %}

djflow/apps/flow/templates/category_list.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{% trans 'Categorías' %}{% endblock %}
{% block page-title %}{% trans 'Lista de Categorías' %}{% endblock %}
{% block nav_category %}active{% endblock %}
{% block add-button %}
     <a href="{% url 'flow:category-new' %}" class="btn btn-outline-primary"><i class="fa fa-plus"></i> {% trans 'Nuevo' %}</a>
{% endblock %}
{% block content %}
    {% if object_list %}
        <table class="table table-sm">
            <thead class="thead-inverse">
            <tr>
                <th>{% trans 'Nombre' %}</th>
                <th>{% trans 'Tipo' %}</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for element in object_list %}
                <tr>
                    <td><a href="{% url 'flow:category-edit' element.pk %}">{{ element.name }}</a></td>
                    <td>
                        {% if element.type == 0 %}
                            {% trans 'Egreso' %}
                        {% else %}
                            {% trans 'Ingreso' %}
                        {% endif %}
                    </td>
                    <td><a href="{% url 'flow:category-delete' element.pk %}" class="btn btn-danger btn-sm btn-flat"><i class="fa fa-trash"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% include 'includes/paginator.html' with url_list='/flow/account/list/' %}
    {% else %}
        <div class="alert alert-info" role="alert">
            <span>{% trans 'Parece que aún no hay categorías registradas' %}</span>
        </div>
    {% endif %}
{% endblock content %}

djflow/apps/flow/templates/comment_list.html
{% extends 'base.html' %}
{% load i18n static humanize %}
{% block title %}{% trans 'Comentarios de transacción' %}{% endblock %}
{% block page-title %}{% trans 'Comentarios de la transacción' %}{% endblock %}
{% block nav_transac %}active{% endblock %}
{% block add-button %}
     <a href="{% url 'flow:transaction-new' %}" class="btn btn-outline-primary" data-toggle="modal" data-target="#add-comment"><i class="fa fa-plus"></i> {% trans 'Nuevo' %}</a>
{% endblock %}
{% block content %}
    {% if object_list %}
        <div class="card widget">
            <div class="card-header">
{#                <h3 class="panel-title">{% trans 'Comentarios' %}</h3>#}
            </div>
            <div class="card-block" style="padding: 0">
                {% include 'includes/comment_list_widget.html' with list_comments=object_list %}
            </div>
        </div>
    {% else %}
        <div class="alert alert-info" role="alert">
            <span>{% trans 'Parece que aún no hay transacciones registradas' %}</span>
        </div>
    {% endif %}



    <!-- Modal -->
    <div class="modal fade" id="add-comment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="{% url 'flow:transaction-comment-new' transaction.id %}" method="post" enctype="multipart/form-data">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{% trans 'Nuevo comentario' %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                        {% csrf_token %}
                        <textarea name="comment" class="form-control" id="" cols="30" rows="10" placeholder="{% trans 'Escribe tu comentario...' %}"></textarea>

                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary">{% trans 'Comentar' %}</button>
                </div>
            </div>
                </form>
        </div>
    </div>

{% endblock content %}

djflow/apps/flow/templates/dashboard.html
{% extends 'base.html' %}
{% load i18n static humanize %}
{% block title %}{% trans 'Dashboard' %}{% endblock %}
{% block page-title %}{% trans 'Dashboard' %}{% endblock %}
{% block nav_dashboard %}active{% endblock %}
{% block add-button %}
    <div class="btn-group" role="group" aria-label="Button group with nested dropdown" style="margin-right: 10px">
        <div class="btn-group" role="group">
            <button id="btnGroupDrop1" type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                <i class="fa fa-plus"></i> {% trans 'Nuevo' %}
            </button>
            <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <a class="dropdown-item" href="{% url 'flow:transaction-new' %}"><i class="fa fa-exchange text-success"></i> {% trans 'Transacción' %}</a>
                <a class="dropdown-item" href="{% url 'flow:account-new' %}"><i class="fa fa-credit-card text-info"></i> {% trans 'Cuenta' %}</a>
                <a class="dropdown-item" href="{% url 'flow:category-new' %}"><i class="fa fa-tag text-primary"></i> {% trans 'Categoría' %}</a>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <section class="row placeholders">
        <div class="col-md-12 col-sm-12 col-xs-12 col-lg-6 placeholder">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-thumbs-o-down text-danger"></i> {% trans 'Gastos por categoría' %}
                </div>
                <div class="card-block" style="padding: 0">
                    <table class="table table-sm">
                        <thead class="bg-danger">
                        <tr>
                            <th>{% trans 'Categoría' %}</th>
                            <th></th>
                            <th class="text-center">{% trans 'Monto' %}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in expense_categories %}
                            <tr>
                                <td align="left">{{ category.name }}</td>
                                <td align="right">$</td>
                                <td align="right">
                                    {% if category.total_amount %}{{ category.total_amount|floatformat:2|intcomma }} {% else %}
                                        0.00{% endif %}</td>
                                <td align="left">[{{ category.transaction_set.count }}]</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12 col-lg-6 placeholder">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-check text-success"></i> {% trans 'Ingresos por categoría' %}
                </div>
                <div class="card-block" style="padding: 0">
                    <table class="table table-sm">
                        <thead class="bg-success">
                        <tr>
                            <th>{% trans 'Categoría' %}</th>
                            <th></th>
                            <th class="text-center">{% trans 'Monto' %}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in income_categories %}
                            <tr>
                                <td align="left">{{ category.name }}</td>
                                <td align="right">$</td>
                                <td align="right">
                                    {% if category.total_amount %}{{ category.total_amount|floatformat:2|intcomma }} {% else %}
                                        0.00{% endif %}</td>
                                <td align="left">[{{ category.transaction_set.count }}]</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <section class="row placeholders">
        <div class="col-md-12 col-sm-12 col-xs-12 col-lg-6 placeholder">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-money"></i> {% trans 'Cuentas' %}
                </div>
                <div class="card-block" style="padding: 0">

                    <table class="table table-sm">
                        <thead class="thead-inverse">
                        <tr>
                            <th>{% trans 'Cuenta' %}</th>
                            <th></th>
                            <th class="text-center">{% trans 'Saldo' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for acct in accounts %}
                            <tr>
                                <td align="left">{{ acct.name }}</td>
                                <td align="right">$</td>
                                <td align="right">
                                    {% if acct.total_amount %}{{ acct.total_amount|floatformat:2|intcomma }} {% else %}
                                        0.00{% endif %}</td>
                            </tr>
                        {% endfor %}


                        </tbody>
                    </table>
                </div>
                <div class="card-footer bg-transparent border-success"><a href="{% url 'flow:account-list' %}"
                                                                          class="pull-right">{% trans 'Ver todos' %}</a>
                </div>
            </div>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12 col-lg-6 placeholder">
            <div class="card">
                <div class="card-header">
                    <i class="fa fa-clock-o"></i> {% trans 'Últimas transacciones' %}
                </div>
                <div class="card-block" style="padding: 0">

                    <table class="table table-sm">
                        <thead class="thead-inverse">
                        <tr>
                            <th>{% trans 'Fecha' %}</th>
                            <th>{% trans 'Cuenta' %}</th>
                            <th></th>
                            <th>{% trans 'Monto' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for t in transactions %}
                            <tr>
                                <td align="left">{{ t.date | date:"SHORT_DATE_FORMAT" }} </td>
                                <td align="left">{{ t.account }}</td>
                                <td>$</td>
                                <td align="right"
                                    class="{% if t.amount > 0 %}text-success{% else %}text-danger{% endif %}"> {{ t.amount|floatformat:2|intcomma }}</td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="card-footer bg-transparent border-success"><a href="{% url 'flow:transaction-list' %}"
                                                                          class="pull-right">{% trans 'Ver todos' %}</a>
                </div>
            </div>


        </div>
    </section>
{% endblock content %}

djflow/apps/flow/templates/transaction_list.html
{% extends 'base.html' %}
{% load i18n static humanize %}
{% block title %}{% trans 'Transacciones' %}{% endblock %}
{% block page-title %}{% trans 'Transacciones' %}{% endblock %}
{% block nav_transac %}active{% endblock %}
{% block add-button %}
     <a href="{% url 'flow:transaction-new' %}" class="btn btn-outline-primary"><i class="fa fa-plus"></i> {% trans 'Nuevo' %}</a>
{% endblock %}
{% block content %}
    {% if object_list %}
        <table class="table table-sm">
        <thead class="thead-inverse text-center">
            <tr>
                <th width="10%" align="center">{% trans 'Registrador' %}</th>
                <th width="35%" align="center">{% trans 'Nombre' %}</th>
                <th width="2%"></th>
                <th width="10%" align="center">{% trans 'Monto' %}</th>
                <th width="10%" align="center">{% trans 'Fecha' %}</th>
                <th width="8%"></th>
            </tr>
        </thead>
        <tbody>
        {% for element in object_list %}
            <tr>
                <td>{{ element.created_by.first_name }} {{ element.created_by.last_name }}</td>
                <td>
                    <a href="{% url 'flow:transaction-edit' element.pk %}">{{ element.name }}</a>
                    <p class="text-gray-dark">
                        <small><b>{% trans 'Categoría' %}</b>: {{ element.category.name }}</small>
                        <br>
                        <small><b>{% trans 'Cuenta' %}</b>: {{ element.account.name }}</small>
                    </p>
                </td>
                <td>$</td>
                <td align="right">{{ element.amount|floatformat:2|intcomma }}</td>
                <td align="center">{{ element.date|date:"d/M/Y" }}</td>
                <td>
                    <a href="{% url 'flow:transaction-comment-list' %}?transaction={{ element.id }}" class="btn btn-sm btn-primary"><i class="fa fa-comments-o"></i> </a>
                    <a href="{% url 'flow:transaction-delete' element.pk %}" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% include 'includes/paginator.html' with url_list='/flow/transaction/list/' %}
    {% else %}
        <div class="alert alert-info" role="alert">
            <span>{% trans 'Parece que aún no hay transacciones registradas' %}</span>
        </div>
    {% endif %}
{% endblock content %}